apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
namespace: jfrog-argo
images:
- name: example
- newName: 440953937617.dkr.ecr.us-east-2.amazonaws.com/spring-boot-repo
  newTag: v3
